version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80 # instedad 8080 use any available port (8080 because 80 is often in use)
    volumes:
      - ./_docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # nginx settings
      - ./:/var/www/html/ # move project files to project webroot
    networks:
      - app

  php:
    build:
      context: ./_docker/php
    depends_on:
      - db
    volumes:
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini # php.ini settings
      - ./:/var/www/html/
    networks:
      - app

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./_docker/mysql/data:/var/lib/mysql # save bd state after docker compose down
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
      - MYSQL_ROOT_PASSWORD=symfony
    networks:
      - app

networks:
  app:
    driver: bridge